#.github/release/yml

changelog:
  categories:
    - title: '✨ 新增内容 / Features'
      labels:
        - PR:feat
    - title: '🐛 错误修复 / Bug Fixes'
      labels:
        - PR:bugfix
    - title: '📝 文档更新 / Documentation'
      labels:
        - PR:docs
    - title: '🔨 代码重构 / Refactor'
      labels:
        - PR:refact
    - title: '🔧 自动化 / CI'
      labels:
        - PR:ci
    - title: '🧶 其他更新 / Others'
      labels:
        - '*'